on: [push]
name: Secrets workflow
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: microsoft/variable-substitution@v1 
      with:
          files: 'DDD.NHibernate.API/appsettings.Production.json'
      env:
        ConnectionStrings.mysql: ${{ secrets.MYSQL }}
      
    
